# Form implementation generated from reading ui file 'portfolio_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 43)
        self.portfolio_base = QtWidgets.QWidget(parent=Form)
        self.portfolio_base.setGeometry(QtCore.QRect(0, 0, 760, 43))
        self.portfolio_base.setMinimumSize(QtCore.QSize(760, 43))
        self.portfolio_base.setMaximumSize(QtCore.QSize(760, 43))
        self.portfolio_base.setObjectName("portfolio_base")
        self.portfolio_base_widget = QtWidgets.QWidget(parent=self.portfolio_base)
        self.portfolio_base_widget.setGeometry(QtCore.QRect(0, 0, 760, 41))
        self.portfolio_base_widget.setMinimumSize(QtCore.QSize(760, 41))
        self.portfolio_base_widget.setMaximumSize(QtCore.QSize(760, 41))
        self.portfolio_base_widget.setStyleSheet("            background-color: #e0e0e0;\n"
"            color: #000000;\n"
"            border-radius: 10px; /* Adjust the value to control the amount of rounding */")
        self.portfolio_base_widget.setObjectName("portfolio_base_widget")
        self.ticker_label = QtWidgets.QLabel(parent=self.portfolio_base_widget)
        self.ticker_label.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.ticker_label.setObjectName("ticker_label")
        self.quantity_label = QtWidgets.QLabel(parent=self.portfolio_base_widget)
        self.quantity_label.setGeometry(QtCore.QRect(160, 10, 51, 21))
        self.quantity_label.setObjectName("quantity_label")
        self.buyingprice_label = QtWidgets.QLabel(parent=self.portfolio_base_widget)
        self.buyingprice_label.setGeometry(QtCore.QRect(280, 10, 91, 21))
        self.buyingprice_label.setObjectName("buyingprice_label")
        self.currprice_label = QtWidgets.QLabel(parent=self.portfolio_base_widget)
        self.currprice_label.setGeometry(QtCore.QRect(450, 10, 81, 21))
        self.currprice_label.setObjectName("currprice_label")
        self.sellButton = QtWidgets.QPushButton(parent=self.portfolio_base_widget)
        self.sellButton.setGeometry(QtCore.QRect(650, 10, 100, 21))
        self.sellButton.setStyleSheet("border: 2px solid #000000;")
        self.sellButton.setObjectName("sellButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ticker_label.setText(_translate("Form", "TICKER"))
        self.quantity_label.setText(_translate("Form", "QTY"))
        self.buyingprice_label.setText(_translate("Form", "BUYING PRICE"))
        self.currprice_label.setText(_translate("Form", "CURR PRICE"))
        self.sellButton.setToolTip(_translate("Form", "Click here to sell shares of this stock!"))
        self.sellButton.setText(_translate("Form", "SELL"))
